version: 0.2

phases:
    install:
        runtime-versions:
            php: 7.3
        commands:
            - echo Nothing to install!
    pre_build:
        commands:
            - composer install --no-progress --no-suggest --no-interaction --classmap-authoritative
