version: 0.2

phases:
    install:
        runtime-versions:
            php: 7.3
        commands:
            - echo Nothing to install!
    pre_build:
        commands:
            - echo Installing Composer dependencies
            - composer install --no-progress --no-suggest --no-interaction --classmap-authoritative
    build:
        commands:
            - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            - docker pull robmeijer/symfony-docker-php-fpm:latest || true
            - docker build --cache-from robmeijer/symfony-docker-php-fpm:latest -f docker/php-fpm/Dockerfile -t robmeijer/symfony-docker-php-fpm:$CODEBUILD_BUILD_ID .
            - docker push robmeijer/symfony-docker-php-fpm:$CODEBUILD_BUILD_ID
            - docker pull robmeijer/symfony-docker-nginx:latest || true
            - docker build --cache-from robmeijer/symfony-docker-nginx:latest -f docker/nginx/Dockerfile -t robmeijer/symfony-docker-nginx:$CODEBUILD_BUILD_ID .
            - docker images
            - docker push robmeijer/symfony-docker-nginx:$CODEBUILD_BUILD_ID
