version: '3.7'

services:
    nginx:
        build:
            context: .
            cache_from:
                - robmeijer/symfony-docker-nginx:latest
            dockerfile: ./docker/nginx/Dockerfile
            target: dev
        image: robmeijer/symfony-docker-nginx:latest
        volumes:
            - ./assets:/app/public
        depends_on:
            - php-fpm
        ports:
            - 80
    php-fpm:
        build:
            context: .
            cache_from:
                - robmeijer/symfony-docker-php-fpm:latest
            dockerfile: ./docker/php-fpm/Dockerfile
            target: dev
        image: robmeijer/symfony-docker-php-fpm:latest
        volumes:
            - .:/app
        command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
